# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QApplication, QDialog, QDialogButtonBox, QLabel
from deskrecover import RegEditor

class CustomDialog(QDialog):
    def __init__(self, msg):
        super().__init__()

        self.setWindowTitle("通知")

        dlg_button = QDialogButtonBox.StandardButton.Ok
        buttonbox = QDialogButtonBox(dlg_button)
        buttonbox.accepted.connect(self.accept)

        layout = QtWidgets.QVBoxLayout()
        label = QtWidgets.QLabel(msg)
        layout.addWidget(label)
        layout.addWidget(buttonbox)
        self.setLayout(layout)

class UiDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(265, 130)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 250, 70))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel()
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel()
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 90, 150, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton()
        self.pushButton_2.setMinimumSize(QtCore.QSize(70, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton()
        self.pushButton.setMinimumSize(QtCore.QSize(70, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "桌面恢复工具"))
        self.label.setText(_translate("Dialog", "上次保存时间："))
        self.label_3.setText(_translate("Dialog", "点击保存，将保存当前的桌面布局"))
        self.label_2.setText(_translate("Dialog", "点击恢复，桌面将恢复为上次保存的布局"))
        self.pushButton_2.setText(_translate("Dialog", "保存"))
        self.pushButton.setText(_translate("Dialog", "恢复"))

class MainWindow(QMainWindow, UiDialog):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setupUi(self)
        # 禁止最大化
        current_size = self.size()
        self.setMaximumSize(current_size)
        self.setMinimumSize(current_size)

        self.desktop_reg = RegEditor()

        self.pushButton.clicked.connect(self.recover_button)
        self.pushButton_2.clicked.connect(self.save_button)

    def save_button(self):
        self.desktop_reg.reg_restore()
        dlg = CustomDialog('保存成功！')
        dlg.exec()

    def recover_button(self):
        self.desktop_reg.reg_read()
        self.desktop_reg.explore_restart()
        dlg = CustomDialog('恢复成功！')
        dlg.exec()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = MainWindow()
    # 定义并显示pyqt主窗口
    w.show()
    # 定义并启动pyqt的事件循环
    app.exec()
